name: "Changelog to release notes"
description: "Extracts a section of a changelog for release notes."
inputs:
  target-version:
    description: "The version heading from which to extract release notes."
    required: true
  changelog-name:
    description: "The name or relative path to the changelog file."
    required: false
    default: "CHANGELOG.md"
  output-filename:
    description: "The name of the file to write the release notes."
    required: false
    default: "release-notes.md"
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Extract version content
      id: extract-contents
      run: extract-content.sh "${{ inputs.target-version }}" "${{ inputs.changelog-name }}" "${{ inputs.output-filename }}"
      shell: bash
